- name: Install NodeJS
  apt:
    name: nodejs
    state: present

- name: Install npm
  apt:
    name: npm
    state: present

- name: Install tsserver
  community.general.npm:
    name: typescript-language-server
    global: true
